import Foundation
import XCTest
@testable import KeyVoxModels

final class ModelFileIntegrityTests: XCTestCase {
    func testStreamsGeneratedBytesAndReportsCompleteProgress() throws {
        // Expected digests independently computed with Python hashlib for locally generated bytes.
        let cases: [(Int, String)] = [
            (0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"),
            (65, "c0a0263ae1ab4e9dda9cd2ed6c44b23ee6ff75c90c640185f462fad7f24fcd6f"),
            (2097189, "ed1e67c8b1feece5731a9c1d108ad789260421a5ddc0caf128832ca73beda423"),
        ]
        for (count, expected) in cases {
            let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            defer { try? FileManager.default.removeItem(at: directory) }
            let url = directory.appendingPathComponent(UUID().uuidString)
            let data = Data((0..<count).map { UInt8(truncatingIfNeeded: $0 &* 31) })
            try data.write(to: url)
            var observed: [(Int64, Int64)] = []
            let digest = try ModelFileIntegrity.sha256Hex(forFileAt: url) { observed.append(($0, $1)) }
            XCTAssertEqual(digest, expected)
            XCTAssertEqual(observed.first?.0, 0)
            XCTAssertEqual(observed.last?.0, Int64(count))
            XCTAssertTrue(observed.allSatisfy { $0.1 == Int64(count) })
            XCTAssertTrue(zip(observed, observed.dropFirst()).allSatisfy { $0.0.0 < $0.1.0 })
            XCTAssertEqual(try Data(contentsOf: url), data)
        }
    }

    func testMissingFileAndDirectoryFail() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        XCTAssertThrowsError(try ModelFileIntegrity.sha256Hex(forFileAt: directory.appendingPathComponent(UUID().uuidString)))
        XCTAssertThrowsError(try ModelFileIntegrity.sha256Hex(forFileAt: directory))
    }
}
